# Generated by Django 4.1.1 on 2022-10-04 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_code', models.CharField(max_length=10)),
                ('sort_key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('type', django_enum.fields.EnumCharField(choices=[('hw', 'Homeworks'), ('nt', 'Notifications'), ('al', 'Alert')], default='hw', max_length=2)),
                ('due_date', models.DateField()),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject')),
            ],
        ),
    ]
