# Generated by Django 4.1.1 on 2022-10-04 12:56

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_homework_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('hw', 'Homeworks'), ('nt', 'Notifications'), ('al', 'Alert')], default='hw', help_text='Type of the homework', max_length=2),
        ),
    ]
