# Generated by Django 4.1.1 on 2022-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_homework_create_date_alter_homework_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.CharField(help_text='The content of the homework, including instructions from the teacher.', max_length=200),
        ),
    ]
