# Generated by Django 4.1.1 on 2022-10-09 03:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_homework_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(default=main.models.get_tomorrow, help_text='The day students should hand in their homework'),
        ),
    ]
